server:
  port: ${port:10086}
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
#      eureka 服务地址。如果是集群，需指定其他集群地址
      defaultZone: ${defaultZone:http://localhost:10086/eureka}
#    不注册自己。集群需注册
#    register-with-eureka: false
#    不拉取服务
#    fetch-registry: false
  server:
#    服务失效剔除时间，默认60s
    eviction-interval-timer-in-ms: 60000
#    关闭自我保护模式，默认打开
    enable-self-preservation: false
